import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { APK_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms & Conditions | AutoBudget",
};

export default function TermsPage() {
  return (
    <>
      {/* NAVIGATION */}
      <nav className="fixed top-4 left-1/2 -translate-x-1/2 z-[1200] flex items-center justify-between w-[min(90vw,600px)] h-14 px-4 rounded-full bg-black1/80 border border-white/10 backdrop-blur-xl">
        <Link href="/" className="flex items-center gap-2.5 text-cream no-underline">
          <Image
            src="/autobudget.png"
            alt="Logo"
            width={28}
            height={28}
            className="w-7 h-7 object-contain rounded-lg"
          />
          <span className="font-serif text-[18px]">AutoBudget</span>
        </Link>
        <a
          href={APK_URL}
          className="inline-flex items-center font-sans text-[12px] font-bold px-5 py-2 rounded-full bg-lime text-black1 hover:-translate-y-0.5 transition"
        >
          Get the App
        </a>
      </nav>

      {/* CONTENT */}
      <main className="pt-[160px] pb-[100px] px-6 max-w-[800px] mx-auto">
        <h1 className="font-serif text-[60px] leading-none mb-4">
          Terms &amp; <span className="italic text-lime">Conditions.</span>
        </h1>
        <p className="font-mono text-sm text-lime mb-12 uppercase tracking-widest">
          Effective Date: April 8, 2026
        </p>

        <div className="space-y-8 text-warm leading-relaxed md:text-lg">
          <section>
            <h2 className="font-serif text-3xl text-cream mb-4 border-b border-white/5 pb-2">
              1. Agreement to Terms
            </h2>
            <p>
              By downloading, installing, or using the AutoBudget application on Android
              (&quot;the App&quot;), you agree to be bound by these Terms and
              Conditions. The App is a completely local-first financial tracking utility
              that categorizes budget items based on incoming bank SMS.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-3xl text-cream mb-4 border-b border-white/5 pb-2">
              2. Liability of Financial Decisions
            </h2>
            <p>
              AutoBudget uses an on-device, deterministic rule engine to interpret
              spending. We do not provide financial advice. You remain entirely
              responsible for your spending habits, debt calculations, limits, and
              real-life banking actions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-3xl text-cream mb-4 border-b border-white/5 pb-2">
              3. Open Source Usage
            </h2>
            <p>
              AutoBudget includes an open-source core distributed under the MIT License.
              AutoBudget Inc. reserves all rights to proprietary visual interfaces,
              branding (AutoBudget logo), the &quot;Spendgate&quot; methodology, and
              compiled non-open assets distributed in production builds (Play Store or
              direct APK download).
            </p>
          </section>

          <section>
            <h2 className="font-serif text-3xl text-cream mb-4 border-b border-white/5 pb-2">
              4. Disclaimers of Warranties
            </h2>
            <p>
              The App relies on reading SMS generated by third-party banks
              (&quot;Your Banks&quot;). Because of changes to OS-level SMS
              permissions, or modifications in SMS phrasing by Your Banks,
              AutoBudget may miss or improperly parse transactions. We do not guarantee
              100% accuracy of ledger tracking or synchronization.
            </p>
          </section>

          <section className="mt-12 bg-black1/50 border border-white/10 p-6 rounded-2xl">
            <h2 className="font-serif text-2xl text-cream mb-2">5. Jurisdiction</h2>
            <p className="font-mono text-sm text-warm/80">
              These Terms will be interpreted under international governing laws,
              exclusively relating strictly to the operation software offline
              capabilities. If you require legal inquiry, contact legal@autobudget.app.
            </p>
          </section>
        </div>
      </main>

      <footer className="flex flex-col md:flex-row items-center justify-between px-10 py-8 border-t border-white/5 text-center md:text-left gap-4 bg-black1">
        <Link
          href="/"
          className="flex items-center gap-3 no-underline hover:opacity-80 transition"
        >
          <Image
            src="/autobudget.png"
            alt="AutoBudget"
            width={24}
            height={24}
            className="w-6 h-6 rounded-[6px]"
          />
          <span className="font-serif text-lg text-cream">AutoBudget</span>
        </Link>
        <div className="flex items-center gap-6 font-mono text-[11px] uppercase tracking-widest">
          <Link href="/privacy" className="text-warm/50 hover:text-lime transition">
            Privacy
          </Link>
          <Link href="/" className="text-warm/50 hover:text-lime transition">
            Home
          </Link>
        </div>
      </footer>
    </>
  );
}
